import { InferSchemaType, Schema, model } from "mongoose";

const userSchema = new Schema(
  {
    _id: {
      // ID generated by Google Oauth, must be called _id to be queried with .findById()
      type: String,
    },
    email: {
      type: String,
      required: true,
    },
    name: {
      type: String,
      required: true,
    },
    targetSleepTime: {
      type: Number,
      required: true,
    },
    score: {
      type: Number,
      default: 0,
    },
  },
  {
    // Automatically generates created and updated times
    timestamps: true,
  }
);

type User = InferSchemaType<typeof userSchema>;

export default model<User>("User", userSchema);
